version: '3'

services:
  db:
    image: postgres:14.0
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    environment:
      - TZ=Asia/Almaty
    env_file:
      - .env
    ports:
      - "5555:5432"
    restart: always

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c 'python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - web_volume:/home/web
      - logs:/home/logs:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - TZ=Asia/Almaty
    env_file:
      - .env
    restart: always

volumes:
  postgres:
  logs:
    external: true
  web_volume:
