# Generated by Django 4.2.5 on 2023-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('cheese', models.CharField(blank=True, null=True, verbose_name='Types of cheese')),
                ('dough', models.CharField(blank=True, null=True, verbose_name='Dough thickness')),
                ('secret_ingredient', models.CharField(blank=True, null=True, verbose_name='Secret ingredient')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PizzeriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Name')),
                ('address', models.CharField(blank=True, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
