# Generated by Django 4.2.5 on 2023-09-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='deleted_at',
            field=models.BooleanField(default=False, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='pizzeriamodel',
            name='deleted_at',
            field=models.BooleanField(default=False, verbose_name='Deleted at'),
        ),
    ]
